Immobilien.WebUI/Controllers/DealController.cs
using AutoMapper;
using Immobilien.Business.Abstract;
using Immobilien.Dto.Dtos.DealDtos;
using Immobilien.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace Immobilien.WebUI.Controllers
{
    public class DealController : Controller
    {

        private readonly IDealService _dealService;
        private readonly IMapper _mapper;

        public DealController(IDealService dealService, IMapper mapper)
        {
            _dealService = dealService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var datas = await _dealService.TGetListAsync();
            var dealList = _mapper.Map<List<ResultDealDto>>(datas);
            return View(dealList);
        }

        public async Task<IActionResult> DeleteDeal(ObjectId id)
        {
            await _dealService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateDeal()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDeal(CreateDealDto createDealDto)
        {
            var newDeal = _mapper.Map<Deal>(createDealDto);
            await _dealService.TCreateAsync(newDeal);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateDeal(ObjectId id)
        {
            var datas = await _dealService.TGetByIdAsync(id);
            var deal = _mapper.Map<UpdateDealDto>(datas);
            return View(deal);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateDeal(UpdateDealDto updateDealDto)
        {
            var deal = _mapper.Map<Deal>(updateDealDto);
            await _dealService.TUpdateAsync(deal);
            return RedirectToAction("Index");
        }

    }
}

Immobilien.WebUI/Controllers/MessageController.cs
using AutoMapper;
using Immobilien.Business.Abstract;
using Immobilien.Dto.Dtos.MessageDtos;
using Immobilien.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace Immobilien.WebUI.Controllers
{
    public class MessageController : Controller
    {

        private readonly IMessageService _messageService;
        private readonly IMapper _mapper;

        public MessageController(IMessageService messageService, IMapper mapper)
        {
            _messageService = messageService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var datas = await _messageService.TGetListAsync();
            var messageList = _mapper.Map<List<ResultMessageDto>>(datas);
            return View(messageList);
        }

        public async Task<IActionResult> DeleteMessage(ObjectId id)
        {
            await _messageService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateMessage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMessage(CreateMessageDto createMessageDto)
        {
            var newMessage = _mapper.Map<Message>(createMessageDto);
            await _messageService.TCreateAsync(newMessage);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> MessageDetails(ObjectId id)
        {
            var data = await _messageService.TGetByIdAsync(id);
            var message = _mapper.Map<ResultMessageDto>(data);
            return View(message);
        }

        //[HttpPost]
        //public async Task<IActionResult> UpdateMessage(UpdateMessageDto updateMessageDto)
        //{
        //    var message = _mapper.Map<Message>(updateMessageDto);
        //    await _messageService.TUpdateAsync(message);
        //    return RedirectToAction("Index");
        //}
    }
}

Immobilien.WebUI/Views/Message/CreateMessage.cshtml
@model CreateMessageDto
@{
    ViewData["Title"] = "Yeni Mesaj Ekleme Sayfasi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <label>Mesaj Tarihi</label>
    <input type="datetime" asp-for="MessageDate" class="form-control" />
    <br />
    <label>Email Adresi</label>
    <input type="text" asp-for="Email" class="form-control" />
    <br />
    <label>Ad Soyad</label>
    <input type="text" asp-for="Name" class="form-control" />
    <br />
    <label>Konu</label>
    <input type="text" asp-for="Subject" class="form-control" />
    <br />
    <label>Mesaj Metni</label>
    <textarea asp-for="MessageContent" class="form-control" rows="10"></textarea>
    <br /> 

    <button class="btn btn-outline-dark">Kaydet</button>
</form>

Immobilien.WebUI/Views/Message/Index.cshtml
@model List<ResultMessageDto>
@{
    ViewData["Title"] = "Gelen Mesajlar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-hover table-bordered">
    @{
        int count = 0;
    }
    <tr>
        <th>#</th>
        <th>Mesaj Tarih</th>
        <th>Email Adresi</th>
        <th>Ad Soyad</th>
        <th>Konu</th>
        @* <th>Mesaj Icerigi</th> *@
        <th>Islemler</th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.MessageDate</td>
            <td>@item.Email</td>
            <td>@item.Name</td>
            <td>@item.Subject</td>
            @* <td>@item.MessageContent</td> *@
            <td>
                @* <a asp-controller="Deal" asp-action="DeleteDeal" asp-route-id="@item.Id" class="btn btn-outline-danger">Sil</a> *@
                <button onclick="DeleteRecord('/Message/DeleteMessage/@item.Id')" class="btn btn-outline-danger">Sil</button>

                @* <button onclick="ShowMessageDetails(this)" id="@item.Id" data-name="@item.Name" data-subject="@item.Subject" data-content="/Message/DeleteMessage/@item.Id" class="btn btn-outline-danger">Sil</button> *@

                <a asp-controller="Message" asp-action="MessageDetails" asp-route-id="@item.Id" class="btn btn-outline-info">Göster</a>
            </td>
        </tr>
    }
</table>

<a asp-controller="Message" asp-action="CreateMessage" class="btn btn-outline-dark">Yeni Mesaj Ekle</a>

@* <script>
    function ShowMessageDetails(button) {
        var id = button.getAttribute("id");
        var name = button.getAttribute("data-name");
        var subject = button.getAttribute("data-subject");
        var deleteLink = button.getAttribute("data-content");
        //debugger;
        //alert(deleteRecordLink)
        Swal.fire({
            title: "'" + name + "' adli kisiden gelen '" + subject + "' konulu mesaji Silmek istiyor musunuz ?", //Are you sure?
            text: "Islemi Geri Almayacaksiniz !", //You won't be able to revert this!
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Evet, Sil !", //Yes, delete it!
            cancelButtonText: "Iptal"
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = deleteLink;
                Swal.fire({
                    title: "Silindi!", //Deleted!
                    text: "Istenen Veri Silindi.", //Your file has been deleted.
                    icon: "success"
                });
            }
        });
    }
</script> *@

Immobilien.WebUI/Views/Message/MessageDetails.cshtml
@model ResultMessageDto
@{
    ViewData["Title"] = "Mesaj Icerigi Sayfasi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-striped">
    <tr>
        <th>Tarih:</th>
        <td>@Model.MessageDate</td>
    </tr>
    <tr>
        <th>Email:</th>
        <td>@Model.Email</td>
    </tr>
    <tr>
        <th>Ad Soyad:</th>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <th>Konu:</th>
        <td>@Model.Subject</td>
    </tr>

    <tr>
        <th>Icerik:</th>
        <td>@Model.MessageContent</td>
    </tr>
</table>

<a asp-controller="Message" asp-action="Index" class="btn btn-dark">Mesajlara Geri Dön</a>