Immobilien.WebUI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace Immobilien.WebUI.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Immobilien.WebUI/Controllers/SendMessageController.cs
using AutoMapper;
using Immobilien.Business.Abstract;
using Immobilien.Dto.Dtos.MessageDtos;
using Immobilien.Entity.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Immobilien.WebUI.Controllers
{
    public class SendMessageController : Controller
    {
        private readonly IMessageService _messageService;
        private readonly IMapper _mapper;

        public SendMessageController(IMessageService messageService, IMapper mapper)
        {
            _messageService = messageService;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> SendMessage(CreateMessageDto createMessageDto)
        {
            var newMessage = _mapper.Map<Message>(createMessageDto);
            await _messageService.TCreateAsync(newMessage);
            return RedirectToAction("Index","Default");
        }
    }
}

Immobilien.WebUI/Views/Shared/Components/_DefaultMessage/Default.cshtml
<div class="col-lg-5">
    <form id="contact-form" asp-controller="SendMessage" asp-action="SendMessage" method="post">
        <div class="row">
            <div class="col-lg-12">
                <fieldset>
                    <label for="name">Ad Soyad</label>
                    <input type="name" name="Name" id="name" placeholder="Adiniz Soyadiniz..."  required>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <label for="email">Email Adresi</label>
                    <input type="text" name="Email" id="email" placeholder="E-mail Adresiniz..." required="">
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <label for="subject">Konu</label>
                    <input type="subject" name="Subject" id="subject" placeholder="Konu..." autocomplete="on">
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <label for="message">Mesaj Iceridi</label>
                    <textarea name="MessageContent" id="message" placeholder="Mesajinizi buraya yazabilirsiniz."></textarea>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <button type="submit" id="form-submit" class="orange-button">Gönder</button>
                </fieldset>
            </div>
        </div>
    </form>
</div>